### ISSUE TITLE
Definición del problema

### ISSUE THREAD

**Issue by DavidLMS** [DavidLMS/greentextbooks#1]

**Comment by dcanoIESRafaelAlberti** [comment]
Editorial más solicitada por provincia?

**Comment by DavidLMS** [comment]
¿Cuáles el top 3 de editoriales elegidas por centros públicos/concertados?

**Comment by mjdiazster** [comment]
Top 3 de editoriales por ciudad andaluza

**Comment by mjdiazster** [comment]
Top 3 editorial por tipo de centro
